minblog/minblog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('about/', views.about,name='about'),
    path('contact/', views.contact,name='contact'),
    path('dashboard/', views.dashboard,name='dashboard'),
    path('signup/', views.user_signup,name='signup'),
    path('login/', views.user_login,name='login'),
    path('logout/', views.user_logout,name='logout'),
    path('addPost/', views.addPost,name='addPost'),
    path('updatePost/<int:id>/', views.updatePost,name='updatePost'),
    path('deletePost/<int:id>/', views.deletePost,name='deletePost'),
]

minblog/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()

minblog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _
from .models import Post

class SignUpForm(UserCreationForm):
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confrom Password (again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ["username","first_name","last_name","email"]
        labels ={'first_name':'First Name','last_name':'Last Name','email':'Email'}
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            }
        
class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus":True,'class':'form-control'}))
    password =forms.CharField(label=_('Password'),strip=False,widget=forms.PasswordInput(attrs={"autocomplete":'current-password','class':'form-control'}))

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title','desc']
        labels = {'title':'Title','desc':'Descriptions  '}
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'desc':forms.Textarea(attrs={'class':'form-control'}),
            }

minblog/blog/views.py
from django.shortcuts import render,redirect
from .models import Post
from .forms import LoginForm, PostForm, SignUpForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User,Group
# from django.contrib.auth.decorators import login_required

# -------------------------------------------------------|
# Home
def home(request):
    post = Post.objects.all()
    return render(request,'blog/home.html',{'posts':post})

# About
def about(request):
    return render(request,'blog/about.html')

# Contact
def contact(request):
    return render(request,'blog/contact.html')

# DashBoard
# @login_required
def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
        user = request.user
        full_name = user.get_full_name()
        gps = user.groups.all()
        return render(request,'blog/dahboard.html',{'posts':posts,'full_name':full_name,'groups':gps})
    else:
        return redirect('/login')

# Signup
def user_signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request,'Congratulations !! You have become a author ✔✔👍')
            # user =User.objects.get()
            group= Group.objects.all()
            for i in group:
                print(i)
            # user.groups.add(group)
    else:
        form = SignUpForm()
    return render(request,'blog/signup.html',{'form':form})

# Login 
def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = LoginForm(request=request,data= request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate( username = uname,password = upass)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Logged in Successfully')
                    return redirect('/dashboard/')
                else:
                    messages.error(request,'username or password is invalid')
        else:
            form = LoginForm()
        return render(request,'blog/login.html',{'form':form})
    else:
        return redirect('/dashboard/')
    
# logout
def user_logout(request):
    logout(request)
    return redirect('/')

# Add a post
def addPost(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = PostForm(request.POST)
            print(form)
            if form.is_valid:
                addtitle = form.cleaned_data['title']
                adddesc = form.cleaned_data['desc']
                pst = Post(title = addtitle, desc= adddesc)
                pst.save()
                print(pst)
                form = PostForm()
        else:
            form = PostForm()
        return render(request,'blog/addpost.html',{'form':form})
    else:
        return redirect('/login/')
    
# Update a Post
def updatePost(request,id):
    if request.user.is_authenticated:
        if request.method == "POST":
            pi = Post.objects.get(pk=id)
            form = PostForm(request.POST,instance=pi)
            if form.is_valid:
                form.save()
        else:
            pi = Post.objects.get(id=id)
            form = PostForm(instance=pi)
        return render(request,'blog/updatepost.html',{'form':form})
    else:
        return redirect('/login/')
    
# Delete post
def deletePost(request,id):
    if request.user.is_authenticated:
        print(id,type())
        if request.method == "Post":
            pi = Post.objects.get(pk=id)
            print(pi,id)
            pi.delete()
            return redirect('dashboard')
    else:
        return redirect('login')

minblog/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class='text-white my-5'>About Page</h3>
    <div class=" py-5">
        <div class="container">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis asperiores sunt dolor assumenda et esse sint quae numquam temporibus rerum voluptas vitae, quisquam molestiae laboriosam blanditiis itaque dicta rem doloremque similique quas neque qui consectetur? Maxime nulla numquam non, facere dolore magni adipisci, iste accusamus tempora velit molestias repellendus! Est!</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eius, quasi non amet omnis ipsam hic? Non temporibus corrupti ratione eveniet at deserunt eos dignissimos nobis animi enim possimus nemo atque quam repellendus cupiditate dolores officiis debitis accusantium omnis eum reiciendis, tempora maiores velit maxime! Porro deserunt explicabo eveniet illo tempore.</p>
        </div>
    </div>
</div>
{% endblock content %}

minblog/blog/templates/blog/addpost.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
   <h3 class='text-white my-5'>Dashboard/ Add Post</h3>
   <form action="" method='post'>
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="ADD" class="btn btn-success">
      <a href="{% url "dashboard" %}" class="btn btn-danger">Cancel</a>
   </form>
 </div>
{% endblock content %}

minblog/blog/templates/blog/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}">
  </head> 
  <body>

    <div class="container-fluid bg-dark">
        {% include "blog/navbar.html" %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}{% endblock msg %}
            </div>
        </div>
        <div class="row">
            {% block side %}{% endblock side %}
            
            {% block content %}{% endblock content %}
        </div>
    </div>

    <script src="{% static "blog/js/jquery.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

minblog/blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class='text-white my-5'>Contact Page</h3>
    <form action="">
        <div class="form row">
            <div class="form-group col-md-6">
                <label for="inputName">Name</label>
                <input type="text" name="" id="inputName" class="form-control">
            </div>
            <div class="form-group col-md-6">
                <label for="inputEmail">Email</label>
                <input type="email" name="" id="inputEmail" class="form-control">
            </div>
        </div>
        <div class="form-group ">
            <label for="address">Address</label><br>
            <textarea class='container-fluid' name="address" id="address" cols="" rows=""></textarea>
        </div>
        <div class="form-group ">
            <label for="message">Message</label><br>
            <textarea class='container-fluid' name="message" id="message" cols="" rows="5"></textarea>
        </div>
        <button class='btn btn-primary' type="submit">Send</button>
    </form>
</div>
{% endblock content %}

minblog/blog/templates/blog/dahboard.html
{% extends "blog/base.html" %}
{% load static %}

{% block msg %}
 {% if messages %}
  {% for msg in messages %}
   <div {% if msg.tags %} class='alert alert-{{msg.tags}} alert-dismissible fade show' {% endif %}>
    <strong>{{msg}}</strong>
    <button type='button' class="close" data-dismiss="alert" area-label="Close">
        <span area-hidden='true'>&times;</span>
    </button>
   </div>
  {% endfor %}
 {% endif %}
{% endblock msg %}

{% block side %}
 <div class="col-sm-2 text-white my-5 text-center">
    <h4 class="my-5">Profile</h4>
    <h5>{{full_name}}</h5>
    {% for group in groups %}
      <p>{{group.name}}</p>
    {% endfor %}
 </div>
{% endblock side %}

{% block content %}
 <div class="col-sm-10">
    <h3 class="text-white my-5">Dasboard Page</h3>
    <a href="{% url "addPost" %}" class="btn btn-success">Add Post</a>
    <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
    {% if posts %}
     <table class="table table-hover bg-white">
        <thead>
            <tr class="text-center">
                
                    <th scope='col' style='width:2%'>ID</th>
                    <th scope='col' style='width:28%'>Title</th>
                    <th scope='col' style='width:55%'>Description</th>
                    <th scope='col' style='width:15%'>Action</th>
                
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
             <tr>
                <th scope='row'>{{post.id}}</th>
                <td>{{post.title}}</td>
                <td>{{post.desc}}</td>
                <td class="text-center">
                    <a href="{% url "updatePost" post.id %}" class="btn btn-warning btn-sm">Edit</a>
                    {% if perms.blog.delete_post %}
                    <a class='btn btn-danger' href="{% url 'deletePost' post.id %}">Delete</a>
                    {% endif %}
                </td>
             </tr>
            {% endfor %}
        </tbody>
     </table>
    {% endif %}
 </div>
{% endblock content %}

minblog/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class='text-white my-5'>Home Page</h3>
    {% for post in posts %}
    <div class="jumbotron jumbotron-fluid jumbo-color py-5 my-5">
        <div class="container">
            <h1 class="display-4 fw-bold">{{post.title}}</h1>
            <p class="lead">{{post.desc}}</p>
        </div>
    </div>
    {% endfor %}    
</div>
{% endblock content %}

minblog/blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class='text-white my-5'>LOGIN Page</h3>
    <div>
        <form action="" method='post' novalidate>
            {% csrf_token %}
            {% for fm in form %}
             <div class="form-group">
              {{fm.label_tag}} {{fm}} <small class='text-warning'> {{fm.error|striptags}}</small>
             </div>
            {% endfor %}
            <input class="btn btn-success mt-2" type="submit" value="Submit">
            {% if form.non_field_errors %}
             {% for error in form.non_field_errors %}
             <p class="alert alert-danger my-3">{{error}}</p>
             {% endfor %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock content %}

minblog/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mini Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "home" %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "about" %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "contact" %}">Contact</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "dashboard" %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link btn text-warning btn-outline-danger " href="{% url "logout" %}">Logout</a>
        </li>
        <li class="nav-item">
          {% else %}
          <a class="nav-link" href="{% url "signup" %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "login" %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

minblog/blog/templates/blog/signup.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class='text-white my-5'>Become an Author</h3>
    {% if messages %}
     {% for msg in messages %}
      <p {% if msg.tags %} class="alert alert-{{msg.tags}}" {% endif %}>{{msg}}</p>
     {% endfor %}
    {% endif %}
    <div>
        <form action="" method='post' novalidate>
            {% csrf_token %}
            {% for fm in form %}
             <div class="form-group">
              {{fm.label_tag}} {{fm}} <small class='text-warning'>{{fm.errors|striptags}}</small>
             </div>
            {% endfor %}
            <input class="btn btn-outline-success mt-2 bg-info" type="submit" value="Submit">
            {% if form.non_field_errors %}
             {% for error in form.non_field_errors %}
             <p class="text-danger">{{error}}</p>
             {% endfor %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock content %}

minblog/blog/templates/blog/updatepost.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
 <h3 class='text-white my-5'>Dashboard/ Update Post</h3>
 <form action="" method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-success">
    <a href="{% url "dashboard" %}" class="btn btn-danger">Cancel</a>
 </form>
{% endblock content %}